trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Dependencies'

- script: npx playwright install
  displayName: 'Install Playwright browsers'
  
- script: npm run smoke
  displayName: 'Run Playwright tests'